language: php

php:
        - "5.4"

script: "VERBOSE=true ./vendor/bin/tester -s -c tests/php.ini-unix -j 29 tests/"

before_script:
        - composer self-update
        - composer install --dev
        - sudo chmod 777 -R ./